services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - backend_uploads:/app/uploads
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - tools-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3031:80"
    depends_on:
      - backend
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - tools-network

volumes:
  backend_uploads:

networks:
  tools-network:
    driver: bridge